In [1]:
import tensorflow as tf
sess = tf.InteractiveSession()

### Making and Initializing Data

### Manually Input Data

In [2]:
x = tf.constant([[2, 5, 3, -5],
                 [0, 3,-2, 5],
                 [4, 3, 5, 3],
                 [6, 1, 4, 0]])

y = tf.constant([[4, -7, 4, -3, 4],
                 [6, 4,-7, 4, 7],
                 [2, 3, 2, 1, 4],
                 [1, 5, 5, 5, 2]])

floatx = tf.constant([[2., 5., 3., -5.],
                      [0., 3.,-2., 5.],
                      [4., 3., 5., 3.],
                      [6., 1., 4., 0.]])

xv = tf.Variable([[2, 5, 3, -5],
                 [0, 3,-2, 5],
                 [4, 3, 5, 3],
                 [6, 1, 4, 0]])

yv = tf.Variable([[4, -7, 4, -3, 4],
                 [6, 4,-7, 4, 7],
                 [2, 3, 2, 1, 4],
                 [1, 5, 5, 5, 2]],trainable=False)

#### `tf.eye()` - Initialize an Identity matrix

In [3]:
tf.eye(5).eval()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [4]:
iv = tf.Variable(tf.eye(4))
iv.initializer.run()
iv.eval()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [6]:
#Create a random 6x10 matrix
A = tf.Variable(tf.random_normal([10,4]))
A.initializer.run()

# elementwise is tf.multiply()
#Multiply two matrices
product = tf.matmul(A, iv).eval()
product

array([[ 0.42024967, -1.7084429 ,  0.11474677,  1.5988508 ],
       [-0.45976564,  0.8524434 , -0.6911082 ,  1.3277458 ],
       [-0.34366554, -1.5231467 , -0.43333977,  0.9084585 ],
       [ 0.18274322,  0.16818914,  0.11447871, -0.9224351 ],
       [-1.3964077 ,  1.1457081 , -0.758443  ,  0.86896116],
       [-0.8240078 , -0.33347732, -0.31896985,  0.04920793],
       [-0.69898313, -0.1582772 ,  0.6387067 ,  0.54621613],
       [-0.63869405, -0.9603468 , -0.02122526,  1.136651  ],
       [-0.47671613,  0.98116803,  0.46481946, -1.6145265 ],
       [-0.92460644, -0.05472356,  0.6745219 ,  1.8333186 ]],
      dtype=float32)

In [7]:
# create a random matrix of 1s and 0s, size 4x10
# tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32)
b = tf.Variable(tf.random_uniform([4,10], 0, 2, dtype= tf.int32))
b.initializer.run()
print(b.eval())

[[1 0 0 0 0 0 1 1 0 0]
 [1 0 1 0 1 1 1 0 1 0]
 [1 0 0 1 1 1 0 0 0 1]
 [1 1 0 1 0 1 0 0 0 1]]


In [8]:
b_new = tf.cast(b.eval().T, dtype=tf.float32) #Cast to float32 data type

# Add the two matrices
t_sum = tf.add(product, b_new)
t_sub = product - b_new
print("A*iv + b\n", t_sum.eval())
print("A*iv - b\n", t_sub.eval()) 

A*iv + b
 [[ 1.4202497  -0.7084429   1.1147468   2.5988507 ]
 [-0.45976564  0.8524434  -0.6911082   2.327746  ]
 [-0.34366554 -0.52314675 -0.43333977  0.9084585 ]
 [ 0.18274322  0.16818914  1.1144787   0.0775649 ]
 [-1.3964077   2.145708    0.241557    0.86896116]
 [-0.8240078   0.6665227   0.68103015  1.0492079 ]
 [ 0.30101687  0.8417228   0.6387067   0.54621613]
 [ 0.36130595 -0.9603468  -0.02122526  1.136651  ]
 [-0.47671613  1.981168    0.46481946 -1.6145265 ]
 [-0.92460644 -0.05472356  1.6745219   2.8333187 ]]
A*iv - b
 [[-0.5797503  -2.708443   -0.88525325  0.59885085]
 [-0.45976564  0.8524434  -0.6911082   0.3277458 ]
 [-0.34366554 -2.5231466  -0.43333977  0.9084585 ]
 [ 0.18274322  0.16818914 -0.8855213  -1.922435  ]
 [-1.3964077   0.14570808 -1.758443    0.86896116]
 [-0.8240078  -1.3334773  -1.3189698  -0.9507921 ]
 [-1.6989832  -1.1582772   0.6387067   0.54621613]
 [-1.638694   -0.9603468  -0.02122526  1.136651  ]
 [-0.47671613 -0.01883197  0.46481946 -1.6145265 ]
 [-0.92460

### Basic Tensor Manipulation

In [10]:
x

<tf.Tensor 'Const:0' shape=(4, 4) dtype=int32>

In [9]:
print(x)
x.eval()

Tensor("Const:0", shape=(4, 4), dtype=int32)


array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  5],
       [ 4,  3,  5,  3],
       [ 6,  1,  4,  0]], dtype=int32)

#### `tf.reshape()`

In [11]:
tf.reshape(x, (2,8)).eval()

array([[ 2,  5,  3, -5,  0,  3, -2,  5],
       [ 4,  3,  5,  3,  6,  1,  4,  0]], dtype=int32)

In [12]:
tf.reshape(x, (8,2)).eval()

array([[ 2,  5],
       [ 3, -5],
       [ 0,  3],
       [-2,  5],
       [ 4,  3],
       [ 5,  3],
       [ 6,  1],
       [ 4,  0]], dtype=int32)

#### `tf.transpose()`

In [16]:
x.eval()

array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  5],
       [ 4,  3,  5,  3],
       [ 6,  1,  4,  0]], dtype=int32)

In [13]:
tf.transpose(x).eval() # Transpose matrix

array([[ 2,  0,  4,  6],
       [ 5,  3,  3,  1],
       [ 3, -2,  5,  4],
       [-5,  5,  3,  0]], dtype=int32)

#### `tf.matmul()`
* Matrix multiplication

In [17]:
tf.matmul(x, y).eval()

array([[ 39, -10, -46,  -8,  45],
       [ 19,  31,   0,  35,  23],
       [ 47,  14,  20,  20,  63],
       [ 38, -26,  25, -10,  47]], dtype=int32)

### Reduction
* Reduction applies an operation across one of the tensor's dimensions, leaving it with one less dimension.
* Operations include (with the same parameters) product, minimum, maximum, mean, all, any, and accumulate_n).

In [25]:
x = tf.constant([[1, 2, 3],[3, 2, 1],[-1,-2,-3]])
x.eval()

array([[ 1,  2,  3],
       [ 3,  2,  1],
       [-1, -2, -3]], dtype=int32)

### `tf.reduce_prod()`

In [20]:
x.eval()

array([[ 1,  2,  3],
       [ 3,  2,  1],
       [-1, -2, -3]], dtype=int32)

In [23]:
tf.reduce_prod(x, reduction_indices=0).eval()

array([-3, -8, -9], dtype=int32)

### `tf.reduce_all()`

In [26]:
boolean_tensor = tf.constant([[True, False, True],[False, False, True],[True, False, True]])
boolean_tensor.eval()

array([[ True, False,  True],
       [False, False,  True],
       [ True, False,  True]])

In [24]:
tf.reduce_all(boolean_tensor, reduction_indices=0).eval()

array([False, False,  True])

### Tensor Slicing and Joining

In [27]:
# create some matrices
t_matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
t_array = tf.constant([1,2,3,4,9,8,6,5])
t_array2= tf.constant([2,3,4,5,6,7,8,9])

### `tf.slice(input_, begin, size)`

In [28]:
t_matrix.eval()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [29]:
tf.slice(t_matrix, [1, 1], [2,2]).eval()

array([[5, 6],
       [8, 9]], dtype=int32)

In [30]:
tf.slice(t_matrix, [1,2], [2,1]).eval()

array([[6],
       [9]], dtype=int32)

### `tf.split()`

In [34]:
t_array.eval()

array([1, 2, 3, 4, 9, 8, 6, 5], dtype=int32)

In [31]:
tf.split(axis=0, num_or_size_splits=2, value=t_array) 

[<tf.Tensor 'split:0' shape=(4,) dtype=int32>,
 <tf.Tensor 'split:1' shape=(4,) dtype=int32>]

In [32]:
print(tf.split(axis=0, num_or_size_splits=2, value=t_array) [0].eval())
print(tf.split(axis=0, num_or_size_splits=2, value=t_array) [1].eval())

[1 2 3 4]
[9 8 6 5]


In [35]:
print(tf.split(axis=0, num_or_size_splits=2, value=t_array).eval())

AttributeError: 'list' object has no attribute 'eval'

### `tf.tile()`

In [36]:
tf.tile([1,2],[3]).eval()

array([1, 2, 1, 2, 1, 2], dtype=int32)

### `tf.pad()`

In [37]:
t_matrix.eval()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [39]:
t_matrix.shape

TensorShape([Dimension(3), Dimension(3)])

In [38]:
tf.pad(t_matrix, [[0,1],[2,1]]).eval()

array([[0, 0, 1, 2, 3, 0],
       [0, 0, 4, 5, 6, 0],
       [0, 0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)

### `tf.concat()`

In [40]:
print(t_array.eval())
print(t_array2.eval())

[1 2 3 4 9 8 6 5]
[2 3 4 5 6 7 8 9]


In [41]:
tf.concat(axis=0, values=[t_array, t_array2]).eval()

array([1, 2, 3, 4, 9, 8, 6, 5, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [43]:
t_matrix.eval()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [42]:
t_matrix2 = tf.concat(axis=0, values=[t_matrix,t_matrix])
t_matrix2.eval()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [44]:
t_matrix3 = tf.concat(axis=1, values=[t_matrix,t_matrix])
t_matrix3.eval()

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]], dtype=int32)

### `tf.stack()`

In [45]:
tf.stack([t_array, t_array2]).eval()

array([[1, 2, 3, 4, 9, 8, 6, 5],
       [2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)

In [46]:
tf.stack([t_array, t_array2],axis=1).eval()

array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5],
       [9, 6],
       [8, 7],
       [6, 8],
       [5, 9]], dtype=int32)

#### `tf.stack()` vs. `tf.concat()`
* If the `axis` parameter is within the range of the existing dimensions, then a new axis will be inserted at that index.

In [47]:
t1 = tf.random_normal([1, 3])
t2 = tf.random_normal([1, 3])

print(tf.stack([t1, t2], axis=1).shape.as_list() == [1, 2, 3])
print(tf.concat([t1, t2], axis=1).shape.as_list() == [1, 6])

True
True


### `tf.unstack()`

In [48]:
sess.run(t_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [49]:
np_matrix = t_matrix.eval()
print(np_matrix)
print(type(np_matrix),np_matrix.dtype)
print()
print(np_matrix[0])
print(type(np_matrix[0]),np_matrix[0].dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'> int32

[1 2 3]
<class 'numpy.ndarray'> int32


In [50]:
unstacked_np_matrix = sess.run(tf.unstack(t_matrix))
print(unstacked_np_matrix)
print(type(unstacked_np_matrix))
print()
print(unstacked_np_matrix[0])
print(type(unstacked_np_matrix[0]))

[array([1, 2, 3], dtype=int32), array([4, 5, 6], dtype=int32), array([7, 8, 9], dtype=int32)]
<class 'list'>

[1 2 3]
<class 'numpy.ndarray'>


In [51]:
np_matrix[0].dtype

dtype('int32')

You can also give `tf.unstack()` `axis` and `name` arguments.

In [52]:
sess.run(tf.unstack(t_matrix, axis=1,name="Unstacked_into_arrays_of_columns"))

[array([1, 4, 7], dtype=int32),
 array([2, 5, 8], dtype=int32),
 array([3, 6, 9], dtype=int32)]

### `tf.reverse()`

In [53]:
tf.reverse(t_matrix, [False,True]).eval()

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]], dtype=int32)

### Elementwise Operations

In [54]:
# Create two random matrices
a = tf.Variable(tf.random_normal([4,5], stddev=2))
b = tf.Variable(tf.random_normal([4,5], stddev=2))

#Element Wise Multiplication
A = a * b

#Multiplication with a scalar 
B = tf.multiply(2.0, A)

# Elementwise division, its result is
C = tf.divide(a,b)

#Element Wise remainder of division
D = tf.mod(a,b)

init_op = tf.global_variables_initializer()
with tf.Session() as sess:     
    sess.run(init_op)     
    writer = tf.summary.FileWriter('graphs', sess.graph)     
    a, b, A_R, B_R, C_R, D_R = sess.run([a , b, A, B, C, D])
    print("a\n",a,"\nb\n",b, "a*b\n", A_R, "\n2*a*b\n", B_R, "\na/b\n", C_R, "\na%b\n", D_R)
    
writer.close() 

a
 [[ 0.9748891  -3.4758568  -0.61576104 -0.9309627   0.93498355]
 [-0.16970812  0.75630325 -2.0760865  -1.6797256  -2.078811  ]
 [ 0.2681403  -1.9302405  -2.042519    2.4187844  -0.8403005 ]
 [-1.1321558   2.7637115   3.5283828   0.5175677  -0.8130753 ]] 
b
 [[ 1.9247587  -1.1157962  -0.9329151  -1.9644786  -2.2444432 ]
 [ 1.8820474   1.654654    0.59735435  0.9618467  -0.831687  ]
 [ 0.13152151  3.9739368   0.49224102 -0.19265108 -1.0293938 ]
 [-1.3907378  -0.60073626 -1.9103026  -3.033884   -1.1804694 ]] a*b
 [[ 1.8764262   3.8783479   0.57445276  1.8288562  -2.0985174 ]
 [-0.31939873  1.2514203  -1.2401593  -1.6156386   1.72892   ]
 [ 0.03526621 -7.670654   -1.0054117  -0.46598142  0.8650001 ]
 [ 1.5745318  -1.6602616  -6.7402787  -1.5702404   0.9598105 ]] 
2*a*b
 [[  3.7528524    7.7566957    1.1489055    3.6577125   -4.197035  ]
 [ -0.63879746   2.5028405   -2.4803185   -3.2312772    3.45784   ]
 [  0.07053243 -15.341308    -2.0108235   -0.93196285   1.7300003 ]
 [  3.1490636   -

### TensorFlow Sequences

In [55]:
tf.range(10).eval()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [56]:
tf.linspace(1.0,10.0,20).eval()

array([ 1.       ,  1.4736842,  1.9473684,  2.4210527,  2.8947368,
        3.368421 ,  3.8421054,  4.315789 ,  4.7894735,  5.263158 ,
        5.736842 ,  6.2105265,  6.684211 ,  7.157895 ,  7.631579 ,
        8.105263 ,  8.578947 ,  9.052631 ,  9.526316 , 10.       ],
      dtype=float32)

In [57]:
sess.close()